/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用户登录
         * @description 管理员登录，返回 JWT Token。
         *     底层认证由 AuthProvider SPI 驱动：
         *     - local：本地数据库（默认）
         *     - remote：远程 OAuth 2.0 / OIDC 服务（Keycloak、Casdoor 等）
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询工作流定义 */
        get: operations["listWorkflows"];
        put?: never;
        /** 创建工作流 */
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取工作流详情 */
        get: operations["getWorkflow"];
        /** 更新工作流 */
        put: operations["updateWorkflow"];
        post?: never;
        /** 删除工作流 */
        delete: operations["deleteWorkflow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/execute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 执行工作流 */
        post: operations["executeWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 发布工作流
         * @description 将工作流从 DRAFT 状态发布为 ACTIVE，并按指定的 PublishTarget 推送到配置中心
         */
        post: operations["publishWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/deprecate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下线工作流
         * @description 将工作流从 ACTIVE 状态变更为 DEPRECATED，并从配置中心移除
         */
        post: operations["deprecateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询工作流历史版本 */
        get: operations["listWorkflowVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 回滚工作流到指定版本 */
        post: operations["rollbackWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/import/openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 导入 OpenAPI 文件 */
        post: operations["importOpenAPI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/import/openapi/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 确认导入 OpenAPI */
        post: operations["confirmImportOpenAPI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/export/openapi": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 导出 OpenAPI（单工作流/全量） */
        get: operations["exportOpenAPI"];
        put?: never;
        /** 批量导出 OpenAPI */
        post: operations["batchExportOpenAPI"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/debug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 调试执行工作流 */
        post: operations["debugWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/debug/node": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 调试单个节点 */
        post: operations["debugWorkflowNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/debug/step": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 单步执行 */
        post: operations["debugWorkflowStep"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/debug/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从节点重跑 */
        post: operations["rerunWorkflowNode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/debug/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询调试执行历史 */
        get: operations["listDebugHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/workflows/{workflowId}/debug/history/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询调试历史详情 */
        get: operations["getDebugHistoryDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询 Schema */
        get: operations["listSchemas"];
        put?: never;
        /** 注册 Schema */
        post: operations["createSchema"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/{schemaName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取 Schema 详情 */
        get: operations["getSchema"];
        /** 更新 Schema */
        put: operations["updateSchema"];
        post?: never;
        /** 删除 Schema */
        delete: operations["deleteSchema"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出数据库中所有用户表 */
        get: operations["listTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/tables/{tableName}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定表的列元数据 */
        get: operations["listTableColumns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/tables/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有表及其列信息，用于设计器侧边栏一次性加载 */
        get: operations["listTablesWithColumns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/tables/{tableName}/foreign-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取指定表的外键信息 */
        get: operations["listForeignKeys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/tables/{tableName}/json-schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 根据表结构生成 JSON Schema，不持久化 */
        get: operations["generateTableJsonSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/schemas/{schemaName}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询 Schema 历史版本 */
        get: operations["listSchemaVersions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/functions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 分页查询函数 */
        get: operations["listFunctions"];
        put?: never;
        /** 注册函数 */
        post: operations["createFunction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/functions/{functionName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取函数详情 */
        get: operations["getFunction"];
        /** 更新函数 */
        put: operations["updateFunction"];
        post?: never;
        /** 删除函数 */
        delete: operations["deleteFunction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/functions/{functionName}/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 测试执行函数 */
        post: operations["testFunction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/decorators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询装饰器参数 Schema */
        get: operations["listDecorators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查询已注册的业务实例
         * @description 返回当前存活的业务实例列表，可按应用群筛选
         */
        get: operations["listInstances"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/instances/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询已注册的应用群列表 */
        get: operations["listInstanceGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询执行历史列表 */
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/executions/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看执行详情 */
        get: operations["getExecution"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/executions/{executionId}/rerun": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 从指定节点重放执行 */
        post: operations["rerunExecution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/executions/{executionId}/signal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向运行中的工作流发送信号（恢复等待节点） */
        post: operations["sendSignal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/executions/{executionId}/signals/waiting": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询工作流正在等待的信号列表 */
        get: operations["getWaitingSignals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/monitor/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取监控指标概览 */
        get: operations["getMetricsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/monitor/metrics/node-latencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取节点平均耗时 */
        get: operations["getNodeLatencies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/monitor/errors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询错误日志 */
        get: operations["listErrorLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/monitor/metrics/trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取请求量趋势 */
        get: operations["getMetricsTrend"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/monitor/traces/{executionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取执行链路详情 */
        get: operations["getTrace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询审计日志 */
        get: operations["listAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/current-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前登录用户及权限 */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询用户列表 */
        get: operations["listUsers"];
        put?: never;
        /** 创建用户 */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户详情 */
        get: operations["getUser"];
        /** 更新用户 */
        put: operations["updateUser"];
        post?: never;
        /** 删除用户 */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查询角色列表 */
        get: operations["listRoles"];
        put?: never;
        /** 创建角色 */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色详情 */
        get: operations["getRole"];
        /** 更新角色 */
        put: operations["updateRole"];
        post?: never;
        /** 删除角色 */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出所有可用的数据源
         * @description 返回 admin 自身已配置的 JDBC 数据源名称列表，供前端函数测试页选择。
         */
        get: operations["listDatasources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/{datasourceId}/tables": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出指定数据源的所有用户表 */
        get: operations["listDatasourceTables"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/datasources/{datasourceId}/tables/{tableName}/columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出指定数据源指定表的所有列元数据 */
        get: operations["listDatasourceTableColumns"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 数据源概要信息 */
        DatasourceInfo: {
            /** @description 数据源唯一标识（等于数据源名称） */
            id?: string;
            /** @description 展示名称 */
            name?: string;
            /** @description 所属域（如 db） */
            domain?: string;
            /** @description 数据源类型（如 admin） */
            type?: string;
        };
        /** @description 表列元数据 */
        DatasourceColumnInfo: {
            /** @description 列名 */
            name?: string;
            /** @description 列名（与 name 同义，兼容前端字段） */
            columnName?: string;
            /** @description 数据库类型名 */
            dataType?: string;
            /** @description 类型（与 dataType 同义，兼容前端字段） */
            type?: string;
            /** @description 列注释 */
            comment?: string;
            /** @description 列描述（与 comment 同义，兼容前端字段） */
            description?: string;
        };
        ErrorResponse: {
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            timestamp?: number;
            status?: number;
            error?: string;
            path?: string;
        };
        /** @enum {string} */
        NodeType: "PARAM_VALIDATE" | "DYNAMIC_VALIDATE" | "DATA_QUERY" | "DATA_TRANSFORM" | "ASSEMBLE_RESPONSE" | "SCRIPT" | "CUSTOM" | "CONDITION_BRANCH" | "FILTER" | "PARALLEL" | "SUB_WORKFLOW" | "EIP_ROUTER" | "LOOP" | "WAIT";
        /** @enum {string} */
        FunctionNodeType: "PARAM_VALIDATE" | "DYNAMIC_VALIDATE" | "DATA_QUERY" | "DATA_TRANSFORM" | "ASSEMBLE_RESPONSE" | "SCRIPT" | "CUSTOM" | "CONDITION_BRANCH" | "FILTER" | "PARALLEL" | "SUB_WORKFLOW" | "EIP_ROUTER" | "LOOP" | "WAIT";
        /** @enum {string} */
        ErrorStrategy: "FAIL" | "IGNORE" | "FALLBACK" | "RETRY";
        /** @enum {string} */
        WorkflowCategory: "BUSINESS" | "META";
        /**
         * @description 工作流作用域：
         *     - PLATFORM: 平台内置，全局共享，仅管理员可修改
         *     - PRIVATE: 应用私有，绑定到特定 app_group
         *     - MARKETPLACE: 市场发布，可被安装
         * @enum {string}
         */
        WorkflowScope: "PLATFORM" | "PRIVATE" | "MARKETPLACE";
        /** @enum {string} */
        WorkflowStatus: "DRAFT" | "ACTIVE" | "DEPRECATED";
        /** @enum {string} */
        FunctionCategory: "BUILTIN" | "CUSTOM" | "SCRIPT" | "EXTERNAL";
        /** @enum {string} */
        FunctionStatus: "ACTIVE" | "INACTIVE";
        /** @enum {string} */
        NodeTraceStatus: "SUCCESS" | "FAILED" | "SKIPPED" | "FALLBACK";
        /** @enum {string} */
        DebugStatus: "RUNNING" | "COMPLETED" | "PAUSED" | "STEP" | "FAILED";
        /**
         * @description 发布目标类型：
         *     - ALL: 全量广播
         *     - APP_GROUP: 按应用群发布
         *     - INSTANCES: 按具体实例发布
         * @enum {string}
         */
        PublishType: "ALL" | "APP_GROUP" | "INSTANCES";
        Position: {
            x?: number;
            y?: number;
        };
        FilterRule: {
            /** @description 字段名（支持点号嵌套路径，如 user.address.city） */
            field: string;
            /**
             * @description 操作符
             * @enum {string}
             */
            operator: "eq" | "neq" | "gt" | "gte" | "lt" | "lte" | "in" | "notIn" | "contains" | "isNull" | "isNotNull" | "startsWith" | "endsWith" | "regex";
            /** @description 规则值（与字段值比较的目标） */
            value?: unknown;
            /**
             * @description 是否对当前规则结果取反
             * @default false
             */
            negate: boolean;
        };
        ConditionalNext: {
            /** @description 条件为 true 时跳转的目标节点 ID */
            target: string;
            /** @description JEXL/SpEL 条件表达式（与 rules 二选一） */
            condition?: string;
            /**
             * @description 多字段组合逻辑
             * @default and
             * @enum {string}
             */
            logic: "and" | "or";
            /**
             * @description 是否对整体条件结果取反（表达式模式或规则组合模式均生效）
             * @default false
             */
            negate: boolean;
            /** @description 结构化规则列表（与 condition 二选一） */
            rules?: components["schemas"]["FilterRule"][];
        };
        WorkflowNode: {
            id: string;
            name: string;
            type: components["schemas"]["NodeType"];
            functionRef: string;
            errorStrategy?: components["schemas"]["ErrorStrategy"];
            /** @default 30000 */
            timeoutMs: number;
            /** @description 工作流各节点输入参数（key=nodeId） */
            params?: {
                [key: string]: unknown;
            };
            decorators?: string[];
            /** @description 工作流各节点输入参数（key=nodeId） */
            decoratorParams?: {
                [key: string]: unknown;
            };
            dependsOn?: string[];
            position?: components["schemas"]["Position"];
            conditionalNexts?: components["schemas"]["ConditionalNext"][];
            /** @description 节点备注（画布显示用） */
            remark?: string;
            /**
             * @description 是否异步执行（true=不阻塞后续节点，异常不中止流程）
             * @default false
             */
            asyncExecution: boolean;
        };
        WorkflowTrigger: {
            id?: string;
            type: components["schemas"]["TriggerType"];
            /**
             * @description 触发器配置（按类型不同结构不同）：
             *     - EVENT: { "eventType": "user.created", "source": "authing" }
             *     - WEBHOOK: { "path": "/hooks/my-workflow" }
             */
            config?: {
                [key: string]: unknown;
            };
            /** @default true */
            enabled: boolean;
        };
        /**
         * @description 触发器类型：
         *     - MANUAL: 手动执行
         *     - WEBHOOK: HTTP POST 触发
         *     - EVENT: 应用事件触发
         *     - API: API 同步调用
         * @enum {string}
         */
        TriggerType: "MANUAL" | "WEBHOOK" | "EVENT" | "API";
        WorkflowDefinition: {
            readonly id?: string;
            name: string;
            category: components["schemas"]["WorkflowCategory"];
            scope?: components["schemas"]["WorkflowScope"];
            /** @description 所属应用分组（scope=PRIVATE 时必填） */
            appGroup?: string;
            /** @description 来源引用（安装市场工作流时指向原始 workflowId） */
            readonly sourceRef?: string;
            protocol: string;
            /**
             * @description 协议方法。HTTP/HTTPS：标准 HTTP 方法（GET/POST/PUT/DELETE 等）；
             *     gRPC：调用类型（UNARY/SERVER_STREAMING 等）；Dubbo：接口方法名（可选）。
             */
            method?: string;
            path?: string;
            status?: components["schemas"]["WorkflowStatus"];
            /** @description 入参 Schema 内容（具体语法由 inputSchemaFormat 决定） */
            inputSchema?: {
                [key: string]: unknown;
            };
            /**
             * @description 入参 Schema 格式标识（如 json-schema、protobuf、avro，支持扩展自定义格式）
             * @default json-schema
             */
            inputSchemaFormat: string;
            /** @description 出参 Schema 内容（具体语法由 outputSchemaFormat 决定） */
            outputSchema?: {
                [key: string]: unknown;
            };
            /**
             * @description 出参 Schema 格式标识（如 json-schema、protobuf、avro，支持扩展自定义格式）
             * @default json-schema
             */
            outputSchemaFormat: string;
            /**
             * @description 事务配置（TransactionConfig 序列化）。
             *     字段示例：{ "propagationBehavior": 0, "isolationLevel": 2, "timeoutMs": 30000, "transactionName": "create-order" }
             *     特殊值 { "mode": "SAGA" } 表示使用 Saga 模式。
             */
            transactionConfig?: {
                [key: string]: unknown;
            };
            /** @description 工作流级装饰器列表（按顺序包裹整段工作流执行） */
            workflowDecorators?: string[];
            /** @description 工作流级装饰器参数（key=装饰器名，value=参数Map） */
            workflowDecoratorParams?: {
                [key: string]: {
                    [key: string]: unknown;
                };
            };
            nodes: components["schemas"]["WorkflowNode"][];
            /** @description 触发器列表（定义工作流的启动方式） */
            triggers?: components["schemas"]["WorkflowTrigger"][];
            publishTarget?: components["schemas"]["PublishTarget"];
            readonly version?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            readonly createdAt?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            readonly updatedAt?: number;
            readonly isProtected?: boolean;
        };
        NodeTrace: {
            nodeId?: string;
            nodeName?: string;
            status?: components["schemas"]["NodeTraceStatus"];
            durationMs?: number;
            /** @description 工作流各节点输入参数（key=nodeId） */
            inputs?: {
                [key: string]: unknown;
            };
            /** @description 工作流各节点输入参数（key=nodeId） */
            output?: {
                [key: string]: unknown;
            };
            error?: string;
        };
        DebugResult: {
            status?: components["schemas"]["DebugStatus"];
            /** @description 工作流各节点输入参数（key=nodeId） */
            snapshot?: {
                [key: string]: unknown;
            };
            traces?: components["schemas"]["NodeTrace"][];
            /** @description 工作流各节点输入参数（key=nodeId） */
            finalOutput?: {
                [key: string]: unknown;
            };
            totalDurationMs?: number;
        };
        DebugExecutionRecord: {
            id?: string;
            workflowId?: string;
            /** Format: int64 */
            timestamp?: number;
            /** @enum {string} */
            status?: "SUCCESS" | "FAILED";
            totalDurationMs?: number;
            /** @description 工作流各节点输入参数（key=nodeId） */
            inputs?: {
                [key: string]: unknown;
            };
            nodeTraces?: components["schemas"]["NodeTrace"][];
            /** @description 工作流各节点输入参数（key=nodeId） */
            finalOutput?: {
                [key: string]: unknown;
            };
            errorMessage?: string;
        };
        InstanceInfo: {
            /** @description 实例唯一标识 */
            instanceId?: string;
            /** @description 所属应用群 */
            appGroup?: string;
            /** @description 实例主机地址 */
            host?: string;
            /** @description 实例端口 */
            port?: number;
            /** @description 实例元数据 */
            metadata?: {
                [key: string]: string;
            };
            /**
             * Format: int64
             * @description 最近一次心跳时间戳（毫秒）
             */
            lastHeartbeatMs?: number;
        };
        AppGroup: {
            /** @description 应用群名称 */
            name?: string;
            /** @description 该群下存活实例数 */
            instanceCount?: number;
        };
        /** @description 发布目标，用于指定工作流/函数推送到哪些实例或应用群 */
        PublishTarget: {
            type?: components["schemas"]["PublishType"];
            /** @description 应用群名称列表（type=APP_GROUP 时必填） */
            groups?: string[];
            /** @description 实例 ID 列表（type=INSTANCES 时必填） */
            instanceIds?: string[];
        };
        /** @enum {string} */
        SchemaType: "INPUT" | "OUTPUT" | "EVENT";
        TableColumnMetadata: {
            /** @description 列名 */
            name?: string;
            /** @description 数据库类型名 */
            dataType?: string;
            /** @description java.sql.Types 常量值 */
            sqlType?: number;
            /** @description 列长度/精度 */
            size?: number;
            /** @description 是否可空 */
            nullable?: boolean;
            /** @description 默认值 */
            defaultValue?: string;
            /** @description 列注释 */
            comment?: string;
            /** @description 列顺序 */
            ordinalPosition?: number;
            /** @description 是否自增 */
            autoIncrement?: boolean;
        };
        TableDetail: {
            /** @description 表名 */
            name?: string;
            /** @description 列元数据列表 */
            columns?: components["schemas"]["TableColumnMetadata"][];
        };
        ForeignKeyInfo: {
            /** @description 外键约束名 */
            fkName?: string | null;
            /** @description 来源表名 */
            sourceTable?: string;
            /** @description 来源列名 */
            sourceColumn?: string;
            /** @description 目标表名 */
            targetTable?: string;
            /** @description 目标列名 */
            targetColumn?: string;
            /** @description 外键列顺序 */
            keySeq?: number;
        };
        ForeignKeysResponse: {
            /** @description 指向当前表的外键 */
            incoming?: components["schemas"]["ForeignKeyInfo"][];
            /** @description 当前表指向其他表的外键 */
            outgoing?: components["schemas"]["ForeignKeyInfo"][];
        };
        SchemaDefinition: {
            /** Format: int64 */
            readonly id?: number;
            /** @description Schema 唯一名称 */
            schemaName: string;
            /** @description 类型标签（逗号分隔，如 INPUT,OUTPUT），支持多类型复用 */
            schemaType: string;
            /**
             * @description Schema 格式标识（如 json-schema、protobuf、avro，支持扩展自定义格式）
             * @default json-schema
             */
            schemaFormat: string;
            /** @description Schema 内容（字符串形式，具体语法由 schemaFormat 决定） */
            schemaJson: string;
            description?: string | null;
            /**
             * @description 是否已冻结（锁定），冻结后普通用户不可修改/删除
             * @default false
             */
            frozen: boolean;
            /**
             * @description 作用域：PLATFORM/PRIVATE
             * @default PLATFORM
             */
            scope: string;
            /** @description 所属应用分组（scope=PRIVATE 时必填） */
            appGroup?: string;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            readonly createdAt?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            readonly updatedAt?: number;
        };
        FunctionDefinition: {
            readonly id?: string;
            name: string;
            category: components["schemas"]["FunctionCategory"];
            nodeType: components["schemas"]["FunctionNodeType"];
            /** @description 脚本引擎，如 groovy/javascript */
            engine?: string;
            /** @description 脚本源码 */
            script?: string;
            /** @description 函数配置 */
            config?: {
                [key: string]: unknown;
            };
            status: components["schemas"]["FunctionStatus"];
            scope?: components["schemas"]["WorkflowScope"];
            /** @description 所属应用分组（scope=PRIVATE 时必填） */
            appGroup?: string;
            /** @description 来源引用（安装市场函数时指向原始 functionName） */
            readonly sourceRef?: string;
            publishTarget?: components["schemas"]["PublishTarget"];
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            readonly createdAt?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            readonly updatedAt?: number;
        };
        MetricsOverview: {
            /** Format: int64 */
            totalRequests?: number;
            /** Format: int64 */
            totalExecutions?: number;
            /** Format: double */
            successRate?: number;
            /** Format: int64 */
            avgDurationMs?: number;
            /** Format: int64 */
            errorCount?: number;
            /** Format: int64 */
            p99LatencyMs?: number;
            activeWorkflows?: number;
        };
        NodeLatency: {
            nodeId?: string;
            nodeName?: string;
            functionRef?: string;
            /** Format: int64 */
            avgDurationMs?: number;
            /** Format: int64 */
            p99DurationMs?: number;
            /** Format: int64 */
            callCount?: number;
        };
        ErrorLog: {
            id?: string;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            time?: number;
            workflowId?: string;
            workflowName?: string;
            nodeId?: string;
            nodeName?: string;
            nodeType?: string;
            errorType?: string;
            message?: string;
            stackTrace?: string;
        };
        TraceDetail: {
            executionId?: string;
            workflowName?: string;
            /** Format: int64 */
            totalDurationMs?: number;
            status?: string;
            traces?: components["schemas"]["TraceNode"][];
        };
        TraceNode: {
            nodeId?: string;
            nodeName?: string;
            /** Format: int64 */
            durationMs?: number;
            status?: string;
            /** @description 工作流各节点输入参数（key=nodeId） */
            inputs?: {
                [key: string]: unknown;
            };
            /** @description 工作流各节点输入参数（key=nodeId） */
            output?: {
                [key: string]: unknown;
            };
            error?: string;
            sql?: string;
        };
        CurrentUser: {
            name?: string;
            avatar?: string;
            roles?: string[];
            /** @description 当前用户拥有的细粒度权限列表（不含 ROLE_ 前缀） */
            permissions?: string[];
            access?: components["schemas"]["UserAccess"];
        };
        UserAccess: {
            canView?: boolean;
            canEdit?: boolean;
            canPublish?: boolean;
            canAdmin?: boolean;
        };
        PageResponseWorkflowDefinition: {
            list?: components["schemas"]["WorkflowDefinition"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResponseFunctionDefinition: {
            list?: components["schemas"]["FunctionDefinition"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResponseSchemaDefinition: {
            list?: components["schemas"]["SchemaDefinition"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResponseDebugExecutionRecord: {
            list?: components["schemas"]["DebugExecutionRecord"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        PageResponseErrorLog: {
            list?: components["schemas"]["ErrorLog"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        RollbackRequest: {
            version: number;
        };
        ImportConfirmRequest: {
            /** @description 待导入的工作流定义列表 */
            items: components["schemas"]["WorkflowDefinition"][];
        };
        OpenAPIExportRequest: {
            ids: string[];
            title?: string;
            version?: string;
        };
        DebugWorkflowRequest: {
            /** @description 工作流各节点输入参数（key=nodeId） */
            inputs?: {
                [key: string]: unknown;
            };
            /** @description 断点节点 ID 列表 */
            breakpoints?: string[];
            mockConfig?: components["schemas"]["MockConfig"];
        };
        DebugNodeRequest: {
            nodeId: string;
            /** @description 工作流各节点输入参数（key=nodeId） */
            inputData?: {
                [key: string]: unknown;
            };
            mockConfig?: components["schemas"]["MockConfig"];
        };
        DebugStepRequest: {
            /** @description 工作流各节点输入参数（key=nodeId） */
            snapshot: {
                [key: string]: unknown;
            };
            breakpoints?: string[];
        };
        DebugRerunRequest: {
            nodeId: string;
            /** @description 工作流各节点输入参数（key=nodeId） */
            snapshot?: {
                [key: string]: unknown;
            };
            /** @description 工作流各节点输入参数（key=nodeId） */
            overrideInput?: {
                [key: string]: unknown;
            };
        };
        /** @description 调试 Mock 配置 */
        MockConfig: {
            /** @default true */
            enabled: boolean;
            rules?: components["schemas"]["MockRule"][];
        };
        /** @description 单条 Mock 规则 */
        MockRule: {
            /** @description 规则唯一标识 */
            id?: string;
            /** @description 目标函数引用 */
            functionRef?: string;
            /** @default true */
            enabled: boolean;
            condition?: components["schemas"]["MockCondition"];
            /** @description 静态响应值（与 responseTemplate 二选一） */
            response?: unknown;
            /** @description 响应模板字符串，支持 ${var} 和 */
            responseTemplate?: string;
            /** @default 0 */
            delayMs: number;
        };
        /** @description Mock 命中条件 */
        MockCondition: {
            /** @description JEXL 条件表达式 */
            expression?: string;
            fieldMatchers?: {
                [key: string]: components["schemas"]["FieldMatcher"];
            };
        };
        /** @description 字段值匹配器 */
        FieldMatcher: {
            exact?: string[];
            startsWith?: string[];
            endsWith?: string[];
            contains?: string[];
        };
        RerunExecutionRequest: {
            nodeId?: string;
        };
        DecoratorDefinition: {
            name: string;
            group?: string;
            label?: string;
            description?: string;
            /** @description 装饰器参数 JSON Schema */
            paramSchema?: {
                [key: string]: unknown;
            };
        };
        ExecutionRecord: {
            executionId?: string;
            workflowId?: string;
            workflowName?: string;
            status?: string;
            /** Format: int64 */
            totalDurationMs?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            startTime?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            endTime?: number;
        };
        PageResponseExecutionRecord: {
            list?: components["schemas"]["ExecutionRecord"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        MetricsTrend: {
            metric?: string;
            interval?: string;
            points?: components["schemas"]["TrendPoint"][];
        };
        TrendPoint: {
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            timestamp?: number;
            /** Format: double */
            value?: number;
        };
        AuditLog: {
            id?: string;
            operator?: string;
            action?: string;
            resourceType?: string;
            resourceId?: string;
            detail?: string;
            ip?: string;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            timestamp?: number;
        };
        PageResponseAuditLog: {
            list?: components["schemas"]["AuditLog"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        User: {
            id?: string;
            username: string;
            nickname?: string;
            email?: string;
            phone?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            roles?: string[];
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            createdAt?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            updatedAt?: number;
        };
        UserRequest: {
            username: string;
            nickname?: string;
            email?: string;
            phone?: string;
            /** @enum {string} */
            status?: "ACTIVE" | "INACTIVE";
            roleIds?: string[];
        };
        PageResponseUser: {
            list?: components["schemas"]["User"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        Role: {
            id?: string;
            name: string;
            code?: string;
            description?: string;
            permissions?: string[];
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            createdAt?: number;
            /**
             * Format: int64
             * @description Unix 毫秒时间戳
             */
            updatedAt?: number;
        };
        RoleRequest: {
            name: string;
            code: string;
            description?: string;
            permissions?: string[];
        };
        PageResponseRole: {
            list?: components["schemas"]["Role"][];
            /** Format: int64 */
            total?: number;
            page?: number;
            pageSize?: number;
        };
        LoginRequest: {
            /** @description 用户名 */
            username: string;
            /** @description 密码 */
            password: string;
        };
        LoginResponse: {
            /** @description JWT 访问令牌 */
            token: string;
            /**
             * @description 令牌类型
             * @example Bearer
             */
            type: string;
        };
    };
    responses: never;
    parameters: {
        /** @description 页码（从 0 开始） */
        Page: number;
        /** @description 每页条数 */
        PageSize: number;
        /** @description 业务实例唯一标识 */
        InstanceIdPath: string;
        WorkflowIdPath: string;
        SchemaNamePath: string;
        TableNamePath: string;
        FunctionNamePath: string;
        ExecutionIdPath: string;
        UserIdPath: string;
        RoleIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description 登录成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description 认证失败 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkflows: {
        parameters: {
            query?: {
                /** @description 关键词（名称/描述） */
                keyword?: string;
                status?: components["schemas"]["WorkflowStatus"];
                category?: components["schemas"]["WorkflowCategory"];
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseWorkflowDefinition"];
                };
            };
        };
    };
    createWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDefinition"];
            };
        };
        responses: {
            /** @description 创建成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowDefinition"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    executeWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description 工作流各节点输入参数（key=nodeId） */
                    inputs?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description 执行成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugResult"];
                };
            };
        };
    };
    publishWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PublishTarget"];
            };
        };
        responses: {
            /** @description 发布成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deprecateWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 下线成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listWorkflowVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"][];
                };
            };
        };
    };
    rollbackWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RollbackRequest"];
            };
        };
        responses: {
            /** @description 回滚成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"];
                };
            };
        };
    };
    importOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file?: string;
                };
            };
        };
        responses: {
            /** @description 导入结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"][];
                };
            };
        };
    };
    confirmImportOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportConfirmRequest"];
            };
        };
        responses: {
            /** @description 确认导入结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDefinition"][];
                };
            };
        };
    };
    exportOpenAPI: {
        parameters: {
            query?: {
                /** @description 工作流 ID 列表（不传则导出全量） */
                ids?: string[];
                title?: string;
                version?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OpenAPI 文档 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "text/yaml": string;
                };
            };
        };
    };
    batchExportOpenAPI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenAPIExportRequest"];
            };
        };
        responses: {
            /** @description OpenAPI 文档 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                    "text/yaml": string;
                };
            };
        };
    };
    debugWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugWorkflowRequest"];
            };
        };
        responses: {
            /** @description 调试结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugResult"];
                };
            };
        };
    };
    debugWorkflowNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugNodeRequest"];
            };
        };
        responses: {
            /** @description 调试结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugResult"];
                };
            };
        };
    };
    debugWorkflowStep: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugStepRequest"];
            };
        };
        responses: {
            /** @description 调试结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugResult"];
                };
            };
        };
    };
    rerunWorkflowNode: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DebugRerunRequest"];
            };
        };
        responses: {
            /** @description 重跑结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugResult"];
                };
            };
        };
    };
    listDebugHistory: {
        parameters: {
            query?: {
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 调试历史列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseDebugExecutionRecord"];
                };
            };
        };
    };
    getDebugHistoryDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflowId: components["parameters"]["WorkflowIdPath"];
                executionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 调试历史详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DebugExecutionRecord"];
                };
            };
        };
    };
    listSchemas: {
        parameters: {
            query?: {
                keyword?: string;
                /** @description 按类型标签过滤（INPUT/OUTPUT/EVENT），仅返回包含该标签的 Schema */
                schemaType?: string;
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseSchemaDefinition"];
                };
            };
        };
    };
    createSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaDefinition"];
            };
        };
        responses: {
            /** @description 注册成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaDefinition"];
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemaName: components["parameters"]["SchemaNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaDefinition"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemaName: components["parameters"]["SchemaNamePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchemaDefinition"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaDefinition"];
                };
            };
        };
    };
    deleteSchema: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemaName: components["parameters"]["SchemaNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listTables: {
        parameters: {
            query?: {
                /** @description 数据源名称，默认使用主数据源 */
                dataSource?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 表名列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    listTableColumns: {
        parameters: {
            query?: {
                /** @description 数据源名称，默认使用主数据源 */
                dataSource?: string;
            };
            header?: never;
            path: {
                tableName: components["parameters"]["TableNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 列元数据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableColumnMetadata"][];
                };
            };
        };
    };
    listTablesWithColumns: {
        parameters: {
            query?: {
                /** @description 数据源名称，默认使用主数据源 */
                dataSource?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 表及其列列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TableDetail"][];
                };
            };
        };
    };
    listForeignKeys: {
        parameters: {
            query?: {
                /** @description 数据源名称，默认使用主数据源 */
                dataSource?: string;
            };
            header?: never;
            path: {
                tableName: components["parameters"]["TableNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 外键信息 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForeignKeysResponse"];
                };
            };
        };
    };
    generateTableJsonSchema: {
        parameters: {
            query?: {
                /** @description 数据源名称，默认使用主数据源 */
                dataSource?: string;
            };
            header?: never;
            path: {
                tableName: components["parameters"]["TableNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 生成的 JSON Schema 字符串 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    listSchemaVersions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                schemaName: components["parameters"]["SchemaNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 版本列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchemaDefinition"][];
                };
            };
        };
    };
    listFunctions: {
        parameters: {
            query?: {
                keyword?: string;
                category?: components["schemas"]["FunctionCategory"];
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseFunctionDefinition"];
                };
            };
        };
    };
    createFunction: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FunctionDefinition"];
            };
        };
        responses: {
            /** @description 注册成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDefinition"];
                };
            };
        };
    };
    getFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionName: components["parameters"]["FunctionNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDefinition"];
                };
            };
            /** @description 未找到 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionName: components["parameters"]["FunctionNamePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FunctionDefinition"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FunctionDefinition"];
                };
            };
        };
    };
    deleteFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionName: components["parameters"]["FunctionNamePath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testFunction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                functionName: components["parameters"]["FunctionNamePath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 函数节点参数（nodeParams），即函数 paramSchema 对应的实例数据 */
                    inputs?: {
                        [key: string]: unknown;
                    };
                    /** @description 直接入参（模拟上游节点输出 / DAG 聚合结果），未传时默认使用 inputs */
                    directInput?: {
                        [key: string]: unknown;
                    };
                    /** @description 工作流原始入参（模拟 workflowInput） */
                    workflowInput?: {
                        [key: string]: unknown;
                    };
                    /** @description 声明依赖节点输出（key 为节点 ID，value 为节点输出） */
                    declaredDeps?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description 测试成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        success?: boolean;
                        /** @description 函数执行输出（任意类型，如对象、数组、字符串、数字等） */
                        output?: unknown;
                        error?: string;
                        /** @description 异常类型（异常类简单名） */
                        errorType?: string;
                        /** @description 异常堆栈摘要（admin 调试用） */
                        errorStack?: string;
                        /**
                         * Format: int64
                         * @description 函数执行耗时（毫秒）
                         */
                        durationMs?: number;
                        /** @description 函数测试执行日志（输入、输出、异常等） */
                        logs?: string[];
                        /** @description 输出是否符合出参 schema（无出参 schema 时默认为 true） */
                        outputValid?: boolean;
                        /** @description 出参 schema 校验错误列表 */
                        validationErrors?: string[];
                    };
                };
            };
        };
    };
    listDecorators: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 装饰器列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DecoratorDefinition"][];
                };
            };
        };
    };
    listInstances: {
        parameters: {
            query?: {
                /** @description 应用群名称（不传则返回全部） */
                group?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 实例列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceInfo"][];
                };
            };
        };
    };
    listInstanceGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 应用群列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppGroup"][];
                };
            };
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                keyword?: string;
                status?: string;
                workflowId?: string;
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 执行历史列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseExecutionRecord"];
                };
            };
        };
    };
    getExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 执行详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
        };
    };
    rerunExecution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RerunExecutionRequest"];
            };
        };
        responses: {
            /** @description 重放结果 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
        };
    };
    sendSignal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description 信号名称 */
                    signalName: string;
                    /** @description 信号携带的数据（任意类型） */
                    data?: unknown;
                };
            };
        };
        responses: {
            /** @description 信号已发送 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executionId?: string;
                        signalName?: string;
                        /** @enum {string} */
                        status?: "DELIVERED" | "BUFFERED";
                    };
                };
            };
            /** @description 信号未被接受（工作流可能未在运行） */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getWaitingSignals: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: components["parameters"]["ExecutionIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 等待中的信号列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        executionId?: string;
                        waiting?: string[];
                        buffered?: string[];
                    };
                };
            };
        };
    };
    getMetricsOverview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsOverview"];
                };
            };
        };
    };
    getNodeLatencies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeLatency"][];
                };
            };
        };
    };
    listErrorLogs: {
        parameters: {
            query?: {
                keyword?: string;
                startTime?: number;
                endTime?: number;
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseErrorLog"];
                };
            };
        };
    };
    getMetricsTrend: {
        parameters: {
            query?: {
                /** @description 指标类型 */
                metric?: "requests" | "successRate" | "latency";
                startTime?: number;
                endTime?: number;
                /** @description 查询最近 N 小时的趋势数据 */
                hours?: number;
                /** @description 聚合粒度 */
                interval?: "1m" | "5m" | "15m" | "1h" | "1d";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 趋势数据 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsTrend"];
                };
            };
        };
    };
    getTrace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TraceDetail"];
                };
            };
        };
    };
    listAuditLogs: {
        parameters: {
            query?: {
                operator?: string;
                action?: string;
                resourceType?: string;
                startTime?: number;
                endTime?: number;
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 审计日志列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseAuditLog"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUser"];
                };
            };
        };
    };
    listUsers: {
        parameters: {
            query?: {
                keyword?: string;
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseUser"];
                };
            };
        };
    };
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 用户详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listRoles: {
        parameters: {
            query?: {
                keyword?: string;
                /** @description 页码（从 0 开始） */
                page?: components["parameters"]["Page"];
                /** @description 每页条数 */
                pageSize?: components["parameters"]["PageSize"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageResponseRole"];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description 创建成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    getRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 角色详情 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 删除成功 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listDatasources: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 数据源列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceInfo"][];
                };
            };
        };
    };
    listDatasourceTables: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 数据源名称（对应 listDatasources 返回的 id） */
                datasourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 表名列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    listDatasourceTableColumns: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                datasourceId: string;
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 列元数据列表 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasourceColumnInfo"][];
                };
            };
        };
    };
}
