-- 批量插入 5 个实用工作流到 wf_definition 表
-- 执行方式: docker exec -i mysql mysql -u root -ppassword --default-character-set=utf8mb4 workflow_platform < seed_workflows.sql
-- 注意: node type 必须使用 FunctionNodeType 枚举值（PARAM_VALIDATE/DATA_QUERY/CUSTOM 等），不能用 BUILTIN

-- 清除旧种子数据
DELETE FROM `wf_definition` WHERE `workflow_id` IN (
  'http-api-users-id','http-api-orders','http-api-orders-list','http-api-counter-visit','http-api-payment-callback'
);

INSERT INTO `wf_definition` (`workflow_id`,`workflow_name`,`dag_json`,`input_schema`,`output_schema`,`protocol`,`method`,`bind_key`,`category`,`version`,`status`,`transaction_mode`,`is_protected`) VALUES

-- 1. 用户信息查询 GET /api/users/{id}
('http-api-users-id','用户信息查询','{"nodes":[{"id":"n1","name":"参数校验","type":"PARAM_VALIDATE","functionRef":"builtin:paramValidate","timeoutMs":3000,"params":{"schema":{"type":"object","required":["id"],"properties":{"id":{"type":"integer","description":"用户ID"}}}},"dependsOn":[]},{"id":"n2","name":"缓存查询","type":"DATA_QUERY","functionRef":"builtin:redisCommand","timeoutMs":2000,"errorStrategy":"SKIP","params":{"command":"GET","args":["user:{id}"]},"dependsOn":["n1"]},{"id":"n3","name":"数据库查询","type":"DATA_QUERY","functionRef":"builtin:dbExecute","timeoutMs":5000,"params":{"tableName":"sys_user","operation":"SELECT","whereKey":"id"},"dependsOn":["n2"]}]}','{"type":"object","required":["id"],"properties":{"id":{"type":"integer","description":"用户ID"}}}','{"type":"object","properties":{"userId":{"type":"integer"},"username":{"type":"string"},"nickname":{"type":"string"},"email":{"type":"string"},"phone":{"type":"string"},"status":{"type":"string"}}}','HTTP','GET','/api/users/{id}','BUSINESS',1,'DRAFT','NONE',0),

-- 2. 创建订单 POST /api/orders
('http-api-orders','创建订单','{"nodes":[{"id":"n1","name":"参数校验","type":"PARAM_VALIDATE","functionRef":"builtin:paramValidate","timeoutMs":3000,"params":{"schema":{"type":"object","required":["userId","items"],"properties":{"userId":{"type":"integer"},"items":{"type":"array","minItems":1,"items":{"type":"object","required":["productId","quantity"],"properties":{"productId":{"type":"string"},"quantity":{"type":"integer","minimum":1}}}},"remark":{"type":"string","maxLength":500}}}},"dependsOn":[]},{"id":"n2","name":"插入订单","type":"DATA_QUERY","functionRef":"builtin:dbExecute","timeoutMs":5000,"params":{"tableName":"biz_order","operation":"INSERT"},"dependsOn":["n1"]},{"id":"n3","name":"发送通知","type":"DATA_QUERY","functionRef":"builtin:httpCall","timeoutMs":3000,"errorStrategy":"SKIP","params":{"url":"http://notification-service/api/notify","method":"POST","body":{"type":"WEBHOOK","recipient":"order-system","title":"新订单","content":"订单已创建"}},"dependsOn":["n2"]}]}','{"type":"object","required":["userId","items"],"properties":{"userId":{"type":"integer","description":"用户ID"},"items":{"type":"array","minItems":1,"description":"商品列表","items":{"type":"object","required":["productId","quantity"],"properties":{"productId":{"type":"string"},"quantity":{"type":"integer","minimum":1}}}},"remark":{"type":"string","maxLength":500,"description":"订单备注"}}}','{"type":"object","properties":{"orderId":{"type":"string"},"status":{"type":"string"},"totalAmount":{"type":"number"},"createdAt":{"type":"string","format":"date-time"}}}','HTTP','POST','/api/orders','BUSINESS',1,'DRAFT','NONE',0),

-- 3. 订单列表查询 GET /api/orders
('http-api-orders-list','订单列表查询','{"nodes":[{"id":"n1","name":"参数校验","type":"PARAM_VALIDATE","functionRef":"builtin:paramValidate","timeoutMs":3000,"params":{"schema":{"type":"object","required":["page","pageSize"],"properties":{"page":{"type":"integer","minimum":0,"default":0},"pageSize":{"type":"integer","minimum":1,"maximum":200,"default":20},"userId":{"type":"integer","description":"按用户筛选"},"status":{"type":"string","enum":["PENDING","PAID","SHIPPED","COMPLETED","CANCELLED"]}}}},"dependsOn":[]},{"id":"n2","name":"查询订单","type":"DATA_QUERY","functionRef":"builtin:dbExecute","timeoutMs":5000,"params":{"tableName":"biz_order","operation":"SELECT"},"dependsOn":["n1"]}]}','{"type":"object","required":["page","pageSize"],"properties":{"page":{"type":"integer","minimum":0,"default":0},"pageSize":{"type":"integer","minimum":1,"maximum":200,"default":20},"userId":{"type":"integer"},"status":{"type":"string","enum":["PENDING","PAID","SHIPPED","COMPLETED","CANCELLED"]}}}','{"type":"object","required":["total","list"],"properties":{"total":{"type":"integer"},"page":{"type":"integer"},"pageSize":{"type":"integer"},"list":{"type":"array","items":{"type":"object"}}}}','HTTP','GET','/api/orders','BUSINESS',1,'DRAFT','NONE',0),

-- 4. 页面访问计数 POST /api/counter/visit
('http-api-counter-visit','页面访问计数','{"nodes":[{"id":"n1","name":"递增计数","type":"DATA_QUERY","functionRef":"builtin:redisCommand","timeoutMs":2000,"params":{"command":"INCR","args":["page:visit:count"]},"dependsOn":[]},{"id":"n2","name":"获取总数","type":"DATA_QUERY","functionRef":"builtin:redisCommand","timeoutMs":2000,"params":{"command":"GET","args":["page:visit:count"]},"dependsOn":["n1"]}]}','{"type":"object","properties":{"page":{"type":"string","description":"页面标识，可选"}}}','{"type":"object","properties":{"count":{"type":"integer","description":"当前访问计数"}}}','HTTP','POST','/api/counter/visit','BUSINESS',1,'DRAFT','NONE',0),

-- 5. 支付结果回调处理 POST /api/payment/callback
('http-api-payment-callback','支付结果回调处理','{"nodes":[{"id":"n1","name":"参数校验","type":"PARAM_VALIDATE","functionRef":"builtin:paramValidate","timeoutMs":3000,"params":{"schema":{"type":"object","required":["orderId","paymentId","amount","success"],"properties":{"orderId":{"type":"string"},"paymentId":{"type":"string"},"amount":{"type":"number"},"success":{"type":"boolean"},"payChannel":{"type":"string","enum":["ALIPAY","WECHAT","UNIONPAY"]}}}},"dependsOn":[]},{"id":"n2","name":"更新订单状态","type":"DATA_QUERY","functionRef":"builtin:dbExecute","timeoutMs":5000,"params":{"tableName":"biz_order","operation":"UPDATE","whereKey":"orderId"},"dependsOn":["n1"]},{"id":"n3","name":"清除订单缓存","type":"DATA_QUERY","functionRef":"builtin:redisCommand","timeoutMs":2000,"errorStrategy":"SKIP","params":{"command":"DEL","args":["order:{orderId}"]},"dependsOn":["n2"]},{"id":"n4","name":"发送支付通知","type":"DATA_QUERY","functionRef":"builtin:httpCall","timeoutMs":3000,"errorStrategy":"SKIP","params":{"url":"http://notification-service/api/notify","method":"POST","body":{"type":"WEBHOOK","recipient":"payment-system","title":"支付回调","content":"支付结果已处理"}},"dependsOn":["n3"]}]}','{"type":"object","required":["orderId","paymentId","amount","success"],"properties":{"orderId":{"type":"string","description":"订单号"},"paymentId":{"type":"string","description":"支付流水号"},"amount":{"type":"number","description":"支付金额"},"success":{"type":"boolean","description":"是否成功"},"payChannel":{"type":"string","enum":["ALIPAY","WECHAT","UNIONPAY"],"description":"支付渠道"}}}','{"type":"object","properties":{"processed":{"type":"boolean"},"orderId":{"type":"string"},"updatedAt":{"type":"string","format":"date-time"}}}','HTTP','POST','/api/payment/callback','BUSINESS',1,'DRAFT','NONE',0);
