package com.fluxion.script.meta

import com.fluxion.core.value.FunctionMeta

/**
 * Function-meta catalog for script-engine built-ins.
 *
 * Values in this object are auto-published into every worker's
 * `FunctionMetaRegistry` so the operator console / schema tooling can
 * discover the input/output contract of `builtin:*` functions without
 * needing a live runtime.
 *
 * Note: this file is regenerated by the `:meta-generator` build task when
 * the underlying function classes change. Manual edits will be overwritten.
 */
object ScriptEngineFunctionMetas {

    /**
     * Built-in Groovy script executor.
     *
     * Accepts either an inline script body (`script`) or a script-reference
     * id (`scriptRef`) that will be resolved through
     * [FunctionConfigSubscriber.get] at execution time.
     */
    @JvmField
    val GROOVY_SCRIPT: FunctionMeta = FunctionMeta.builder("builtin:groovyScript")
        .description("Execute a Groovy script. Supports inline body (script) or named reference (scriptRef); compiled classes are cached in a bounded Caffeine cache.")
        .domain("script")
        .paramSchema(
            """
{
    "type": "object",
    "properties": {
        "script": {
            "type": "string",
            "description": "Inline Groovy script body (inline mode)."
        },
        "scriptRef": {
            "type": "string",
            "description": "Named script reference id (initScript mode — resolved via FunctionConfigSubscriber)."
        }
    }
}
            """
        )
        .build()

}
