package com.fluxion.admin.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.ForeignKey
import jakarta.persistence.Index
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import org.hibernate.annotations.JdbcTypeCode
import org.hibernate.type.SqlTypes
import java.time.LocalDateTime

/**
 * Debug-sandbox instance record — one row per "click debug" session / per
 * bound base-resource. Created by [SandboxManager] on first touch of a
 * debug session, cleaned up by the hourly `SandboxCleanupScheduler` or on
 * explicit release from the UI.
 *
 * Sandbox strategy matches the user-chosen policy (defaults to
 * DB_TABLE_PREFIX which is DB-agnostic and does not require CREATE DATABASE
 * rights):
 *
 *   - **DB_TABLE_PREFIX**   → `connection_config.tablePrefix` is prepended to
 *                             every table name when executing SQL against this
 *                             sandbox.  Real: `order_header`, Sandbox:
 *                             `sandbox_sessXYZ_order_header` with identical
 *                             column layout (CREATE TABLE … LIKE).
 *   - **REDIS_DB_INDEX**    → a dedicated numeric Redis DB is assigned;
 *                             `connection_config.redisDbIndex` records it.
 *                             Cleanup = FLUSHDB on that index.
 *   - **KAFKA_TOPIC_PREFIX**→ every topic produced/consumed within the debug
 *                             run gets the configured prefix appended; cleanup
 *                             deletes matching topics.
 *
 * Source table: `sandbox_instance` (Flyway V17).
 */
@Entity
@Table(
    name = "sandbox_instance",
    indexes = [
        Index(name = "idx_app_lifecycle",     columnList = "app_id, lifecycle"),
        Index(name = "idx_expired_lifecycle", columnList = "expired_at, lifecycle"),
        Index(name = "idx_owner_session",     columnList = "owner_session")
    ]
)
class SandboxInstance : BaseEntity() {

    /** Owning app — FK → app.id. */
    @ManyToOne(optional = false)
    @JoinColumn(name = "app_id", nullable = false, foreignKey = ForeignKey(name = "fk_sandbox_app"))
    lateinit var app: App

    /** Base resource cloned — FK → app_resource.id. */
    @ManyToOne(optional = false)
    @JoinColumn(name = "base_resource_id", nullable = false, foreignKey = ForeignKey(name = "fk_sandbox_resource"))
    lateinit var baseResource: AppResource

    /** DB_TABLE_PREFIX / REDIS_DB_INDEX / KAFKA_TOPIC_PREFIX. */
    @Column(name = "sandbox_type", nullable = false, length = 32)
    var sandboxType: String = ""

    /**
     * Free-form strategy-specific context:
     *   DB_TABLE_PREFIX   → `{ tablePrefix, createdTables:["..."], cloneSchemaFrom:["..."] }`
     *   REDIS_DB_INDEX    → `{ redisDbIndex: 5 }`
     *   KAFKA_TOPIC_PREFIX→ `{ topicPrefix, createdTopics:["..."] }`
     */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "connection_config", nullable = false, columnDefinition = "JSON")
    var connectionConfig: MutableMap<String, Any?> = mutableMapOf()

    /** CREATING / READY / IN_USE / EXPIRED / CLEANING / CLEANED / FAILED. */
    @Column(name = "lifecycle", nullable = false, length = 16)
    var lifecycle: String = "CREATING"

    /** Scheduler cutoff — sandboxes older than this get cleaned up. */
    @Column(name = "expired_at", nullable = false)
    var expiredAt: LocalDateTime = LocalDateTime.now().plusHours(4)

    /** LRU refresh on every sandbox SQL/Redis operation. */
    @Column(name = "last_used_at")
    var lastUsedAt: LocalDateTime? = null

    /** Debug-session identifier generated by the UI (maps to multiple sandboxes/resource-type). */
    @Column(name = "owner_session", length = 64)
    var ownerSession: String? = null

    /** Username for audit + force-cleanup by owner. */
    @Column(name = "owner_username", length = 64)
    var ownerUsername: String? = null
}
