package com.fluxion.admin.controller

import com.fluxion.admin.entity.App
import com.fluxion.admin.entity.AppResource
import com.fluxion.admin.entity.AppResourceBinding
import com.fluxion.admin.generated.api.AppsApi
import com.fluxion.admin.generated.api.ResourcesApi
import com.fluxion.admin.generated.model.App as GeneratedApp
import com.fluxion.admin.generated.model.AppBinding
import com.fluxion.admin.generated.model.AppBindingCreateRequest
import com.fluxion.admin.generated.model.AppBindingUpdateRequest
import com.fluxion.admin.generated.model.AppCreateRequest
import com.fluxion.admin.generated.model.AppUpdateRequest
import com.fluxion.admin.generated.model.Resource as GeneratedResource
import com.fluxion.admin.generated.model.ResourceCreateRequest
import com.fluxion.admin.generated.model.ResourceOption
import com.fluxion.admin.generated.model.ResourceUpdateRequest
import com.fluxion.admin.service.AppResourceCenter
import org.slf4j.LoggerFactory
import org.slf4j.warn
import org.slf4j.info
import org.slf4j.error
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RestController
import java.nio.file.FileSystems
import java.nio.file.PathMatcher
import java.nio.file.Paths
import java.time.ZoneId

// ──────────────────────────────────────────────────────────────────────────────
// App center — contract-driven, implemented from AppsApi generated by doc/openapi.yaml.
// DO NOT manually add @GetMapping / @PathVariable / @RequestBody to controller methods.
// ──────────────────────────────────────────────────────────────────────────────
@RestController
class AppController(
    private val center: AppResourceCenter
) : AppsApi {
    private val log = LoggerFactory.getLogger(javaClass)

    // ── Apps CRUD ──────────────────────────────────────────────────────────

    override fun listApps(): ResponseEntity<List<GeneratedApp>> =
        ResponseEntity.ok(center.findAllApps().map { it.toGenerated() })

    override fun getApp(id: Long): ResponseEntity<GeneratedApp> {
        val app = center.findAppById(id) ?: return ResponseEntity.notFound().build()
        return ResponseEntity.ok(app.toGenerated())
    }

    override fun createApp(req: AppCreateRequest): ResponseEntity<GeneratedApp> = try {
        val created = center.createApp(
            AppResourceCenter.AppCreateDto(
                appKey = req.appKey,
                appName = req.appName,
                description = req.description,
                owner = req.owner,
                status = req.status?.value
            )
        )
        ResponseEntity.status(HttpStatus.CREATED).body(created.toGenerated())
    } catch (e: IllegalArgumentException) {
        log.warn("createApp failed: ${e.message}")
        ResponseEntity.badRequest().build()
    }

    override fun updateApp(id: Long, req: AppUpdateRequest): ResponseEntity<GeneratedApp> = try {
        ResponseEntity.ok(
            center.updateApp(
                id,
                AppResourceCenter.AppUpdateDto(
                    appName = req.appName,
                    description = req.description,
                    owner = req.owner,
                    status = req.status?.value
                )
            ).toGenerated()
        )
    } catch (e: IllegalArgumentException) {
        ResponseEntity.notFound().build()
    }

    override fun deleteApp(id: Long): ResponseEntity<Unit> = try {
        center.deleteApp(id)
        ResponseEntity.noContent().build()
    } catch (e: IllegalArgumentException) {
        ResponseEntity.notFound().build()
    }

    // ── Bindings ───────────────────────────────────────────────────────────

    override fun listAppBindings(id: Long): ResponseEntity<List<AppBinding>> =
        ResponseEntity.ok(center.listBindings(id).map { it.toGenerated() })

    override fun listAppResourceOptions(id: Long, resourceType: String): ResponseEntity<List<ResourceOption>> =
        ResponseEntity.ok(center.listAppResourceOptions(id, resourceType).map { it.toGenerated() })

    override fun createAppBinding(id: Long, req: AppBindingCreateRequest): ResponseEntity<AppBinding> = try {
        val created = center.bindResource(
            id,
            AppResourceCenter.BindingCreateDto(
                resourceId = req.resourceId,
                aliasInApp = req.aliasInApp,
                resourceScope = req.scope?.value
            )
        )
        ResponseEntity.status(HttpStatus.CREATED).body(created.toGenerated())
    } catch (e: IllegalArgumentException) {
        log.warn("createAppBinding appId=$id failed: ${e.message}")
        ResponseEntity.badRequest().build()
    }

    override fun updateAppBinding(id: Long, bindingId: Long, req: AppBindingUpdateRequest): ResponseEntity<AppBinding> =
        try {
            ResponseEntity.ok(
                center.updateBinding(
                    id, bindingId,
                    AppResourceCenter.BindingUpdateDto(
                        aliasInApp = req.aliasInApp,
                        resourceScope = req.scope?.value
                    )
                ).toGenerated()
            )
        } catch (e: IllegalArgumentException) {
            ResponseEntity.notFound().build()
        }

    override fun deleteAppBinding(id: Long, bindingId: Long): ResponseEntity<Unit> = try {
        center.unbind(id, bindingId)
        ResponseEntity.noContent().build()
    } catch (e: IllegalArgumentException) {
        ResponseEntity.notFound().build()
    }

    // ── Entity → Generated DTO converters ──────────────────────────────────

    private fun App.toGenerated(): GeneratedApp {
        val statusEnum = when (status.uppercase()) {
            "ACTIVE" -> GeneratedApp.Status.ACTIVE
            "DISABLED", "INACTIVE" -> GeneratedApp.Status.DISABLED
            else -> GeneratedApp.Status.ACTIVE
        }
        val createdAtMs = createdAt.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
        val updatedAtMs = updatedAt.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
        return GeneratedApp(
            id = id,
            appKey = appKey,
            appName = appName,
            status = statusEnum,
            createdAt = createdAtMs,
            updatedAt = updatedAtMs
        ).apply {
            description = this@toGenerated.description
            owner = this@toGenerated.owner
        }
    }

    private fun AppResourceBinding.toGenerated(): AppBinding {
        val scopeEnum = when (resourceScope.uppercase()) {
            "READONLY", "READ_ONLY" -> AppBinding.Scope.READONLY
            "READWRITE", "READ_WRITE" -> AppBinding.Scope.READWRITE
            "ADMIN" -> AppBinding.Scope.ADMIN
            else -> AppBinding.Scope.READWRITE
        }
        return AppBinding(
            id = id,
            appId = app.id,
            resourceId = resource.id,
            resourceName = resource.resourceName,
            resourceType = resource.resourceType,
            scope = scopeEnum,
            effectiveAlias = effectiveAlias()
        ).apply {
            driver = resource.driver
            aliasInApp = this@toGenerated.aliasInApp
        }
    }

    private fun AppResourceCenter.ResourceOption.toGenerated(): ResourceOption {
        val displayLabel = "$alias — $resourceName"
        return ResourceOption(
            resourceId = resourceId,
            alias = alias,
            label = displayLabel,
            resourceType = resourceType,
            driver = driver
        )
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Resource catalog — contract-driven, implemented from ResourcesApi generated by doc/openapi.yaml.
// Sensitive fields (password/secret/token...) are redacted in GET responses.
// The `<REDACTED>` token indicates "keep original value unchanged" (user didn't modify password during update).
// Server-side filters these tokens before applying changes.
// ──────────────────────────────────────────────────────────────────────────────
@RestController
class ResourceCatalogController(
    private val center: AppResourceCenter
) : ResourcesApi {
    private val log = LoggerFactory.getLogger(javaClass)

    override fun listResources(resourceType: String?): ResponseEntity<List<GeneratedResource>> =
        ResponseEntity.ok(center.findAllResources(resourceType).map { it.toSanitizedGenerated() })

    override fun getResource(id: Long): ResponseEntity<GeneratedResource> {
        val r = center.findResourceById(id) ?: return ResponseEntity.notFound().build()
        return ResponseEntity.ok(r.toSanitizedGenerated())
    }

    override fun createResource(req: ResourceCreateRequest): ResponseEntity<GeneratedResource> = try {
        val created = center.createResource(
            AppResourceCenter.ResourceCreateDto(
                resourceName = req.resourceName,
                resourceType = req.resourceType.value,
                driver = req.driver,
                configJson = req.configJson.toMap()
            )
        )
        ResponseEntity.status(HttpStatus.CREATED).body(created.toSanitizedGenerated())
    } catch (e: IllegalArgumentException) {
        ResponseEntity.badRequest().build()
    }

    override fun updateResource(id: Long, req: ResourceUpdateRequest): ResponseEntity<GeneratedResource> = try {
        val rawCfg = req.configJson ?: emptyMap()
        val persisted = (rawCfg as Map<String, Any?>).filterValues { it != null } as Map<String, Any>
        val sanitized = persisted.mapValues { (k, v) ->
            if (v is String && v == SENSITIVE_REDACTED_TOKEN) null else v
        }.filterValues { it != null } as Map<String, Any>
        val next = center.updateResource(
            id,
            AppResourceCenter.ResourceUpdateDto(
                resourceName = req.resourceName,
                resourceType = req.resourceType?.value,
                driver = req.driver,
                configJson = sanitized
            )
        )
        ResponseEntity.ok(next.toSanitizedGenerated())
    } catch (e: IllegalArgumentException) {
        ResponseEntity.notFound().build()
    }

    override fun deleteResource(id: Long): ResponseEntity<Unit> = try {
        center.deleteResource(id)
        ResponseEntity.noContent().build()
    } catch (e: org.springframework.dao.DataIntegrityViolationException) {
        log.warn("deleteResource id=$id FK restrict: ${e.message}")
        ResponseEntity.status(HttpStatus.CONFLICT).build()
    } catch (e: IllegalArgumentException) {
        log.warn("deleteResource id=$id failed: ${e.message}", e)
        ResponseEntity.status(HttpStatus.CONFLICT).build()
    }

    // ── Helpers ────────────────────────────────────────────────────────────

    private fun AppResource.toSanitizedGenerated(): GeneratedResource {
        val sanitizedCfg = (configJson as Map<String, Any?>).mapValues { (k, v) ->
            if (isSensitiveKey(k)) SENSITIVE_REDACTED_TOKEN else v
        }.filterValues { it != null }.toMutableMap() as MutableMap<String, Any>
        val createdAtMs = createdAt.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
        val updatedAtMs = updatedAt.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
        return GeneratedResource(
            id = id,
            resourceType = com.fluxion.admin.generated.model.ResourceType.valueOf(resourceType),
            resourceName = resourceName,
            configJson = sanitizedCfg,
            createdAt = createdAtMs,
            updatedAt = updatedAtMs
        ).apply {
            driver = this@toSanitizedGenerated.driver
        }
    }

    private fun isSensitiveKey(key: String): Boolean {
        val lower = key.lowercase()
        return SENSITIVE_MATCHERS.any { it.matches(lower) }
    }

    companion object {
        const val SENSITIVE_REDACTED_TOKEN = "<REDACTED>"
        private val SENSITIVE_GLOBS = listOf(
            "*password*", "*secret*", "*token*",
            "*sasljaas*", "*privatekey*", "*private_key*",
            "*apikey*", "*api_key*", "*clientsecret*",
            "*client_secret*", "*credentials*"
        )
        private val SENSITIVE_MATCHERS: List<PathMatcher> = SENSITIVE_GLOBS.map { glob ->
            FileSystems.getDefault().getPathMatcher("glob:$glob")
        }

        private fun PathMatcher.matches(key: String): Boolean = this.matches(Paths.get(key))
    }
}
