package com.fluxion.admin.controller

import com.fluxion.admin.entity.WfDefinition
import com.fluxion.admin.generated.api.FunctionSetsApi
import com.fluxion.admin.generated.api.SchemaToolsApi
import com.fluxion.admin.generated.model.CanComposeAfterRequest
import com.fluxion.admin.generated.model.CompatDiagnostic
import com.fluxion.admin.generated.model.CompatResult as GCompatResult
import com.fluxion.admin.generated.model.CompositionResult as GCompositionResult
import com.fluxion.admin.generated.model.FunctionSetDTO
import com.fluxion.admin.generated.model.PublishFunctionSetRequest
import com.fluxion.admin.generated.model.SchemaApplyMappingRequest
import com.fluxion.admin.generated.model.SchemaCompatCheckRequest
import com.fluxion.admin.service.CompositionResult as SvcCompositionResult
import com.fluxion.admin.service.CompatResult as SvcCompatResult
import com.fluxion.admin.service.FunctionSetService
import com.fluxion.admin.service.SchemaCompatibilityService
import com.fluxion.admin.service.TypeMismatch
import org.slf4j.LoggerFactory
import org.slf4j.*
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RestController
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.collections.mutableListOf
import kotlin.collections.toMutableList

/**
 * OpenAPI contract-driven: FunctionSets implemented from [FunctionSetsApi] generated by doc/openapi.yaml.
 * Controller only implements the interface; no Spring MVC annotations are written manually.
 */
@RestController
class FunctionSetController(
    private val sets: FunctionSetService,
    private val compat: SchemaCompatibilityService
) : FunctionSetsApi {
    private val log = LoggerFactory.getLogger(javaClass)

    override fun publishFunctionSet(
        definitionId: Long,
        publishFunctionSetRequest: PublishFunctionSetRequest?
    ): ResponseEntity<FunctionSetDTO> = try {
        val wf = sets.publish(definitionId, publishFunctionSetRequest?.setRefName)
        ResponseEntity.status(HttpStatus.CREATED).body(wf.toDTO())
    } catch (e: IllegalArgumentException) {
        log.warn { "Publish id=$definitionId failed: ${e.message}" }
        ResponseEntity.badRequest().build()
    }

    override fun unpublishFunctionSet(
        definitionId: Long
    ): ResponseEntity<FunctionSetDTO> = try {
        ResponseEntity.ok(sets.unpublish(definitionId).toDTO())
    } catch (e: IllegalArgumentException) {
        ResponseEntity.notFound().build()
    }

    override fun listFunctionSets(
        appId: Long?,
        scope: String?
    ): ResponseEntity<List<FunctionSetDTO>> =
        ResponseEntity.ok(sets.listPublishedSets(appId, scope).map { it.toDTO() })

    override fun canComposeAfterFunctionSet(
        canComposeAfterRequest: CanComposeAfterRequest
    ): ResponseEntity<GCompositionResult> = try {
        val r = sets.canComposeAfter(
            canComposeAfterRequest.setARefName,
            canComposeAfterRequest.setBRefName,
            canComposeAfterRequest.inputMapping
        )
        ResponseEntity.ok(r.toGenerated())
    } catch (e: IllegalArgumentException) {
        val empty = GCompositionResult(compatible = false)
        empty.errors = mutableListOf(requireNotNull(e.message) { "Unknown function set ref" })
        empty.missingRequired = mutableListOf()
        empty.typeMismatches = mutableListOf()
        empty.unmappedOptional = mutableListOf()
        ResponseEntity.ok(empty)
    }

    // ── DTO Converters ────────────────────────────────────────────

    private fun WfDefinition.toDTO(): FunctionSetDTO {
        val dto = FunctionSetDTO(
            id = id,
            workflowId = workflowId,
            workflowName = workflowName,
            published = isPublishedSet,
            status = FunctionSetDTO.Status.forValue(status),
            scope = FunctionSetDTO.Scope.forValue(scope),
            category = FunctionSetDTO.Category.forValue(category)
        )
        dto.setRefName = setRefName
        dto.protocol = protocol
        dto.appGroup = appGroup
        dto.inputSchemaPresent = !inputSchema.isNullOrBlank()
        dto.outputSchemaPresent = !outputSchema.isNullOrBlank()
        dto.version = version
        dto.owner = createdBy
        return dto
    }

    private fun SvcCompositionResult.toGenerated(): GCompositionResult {
        val compatDTO = diagnostics.toGenerated()
        val r = GCompositionResult(
            compatible = ok
        )
        r.sourceFields = compatDTO.sourceFields
        r.targetRequiredCount = compatDTO.targetRequiredCount
        r.missingRequired = compatDTO.missingRequired
        r.typeMismatches = compatDTO.typeMismatches
        r.unmappedOptional = compatDTO.unmappedOptional
        r.setAWorkflowId = A
        r.setBWorkflowId = B
        r.mappingApplied = false
        r.errors = mutableListOf()
        return r
    }
}

/**
 * OpenAPI contract-driven: SchemaTools implemented from [SchemaToolsApi] generated by doc/openapi.yaml.
 */
@RestController
class SchemaCompatibilityController(
    private val compat: SchemaCompatibilityService
) : SchemaToolsApi {

    override fun checkSchemaCompatibility(
        schemaCompatCheckRequest: SchemaCompatCheckRequest
    ): ResponseEntity<GCompatResult> {
        val result = compat.checkWithMapping(
            schemaCompatCheckRequest.sourceSchema,
            schemaCompatCheckRequest.targetSchema,
            schemaCompatCheckRequest.mappingJson
        )
        return ResponseEntity.ok(result.toGenerated())
    }

    override fun applySchemaMapping(
        schemaApplyMappingRequest: SchemaApplyMappingRequest
    ): ResponseEntity<Map<String, Any>> {
        val mapped = compat.applyMappingJson(
            schemaApplyMappingRequest.sourcePayloadJson,
            schemaApplyMappingRequest.mappingJson
        )
        // Any? -> Any narrowing: Jackson can serialize directly, with null-safe fallback
        val safe = mapped.mapValues { it.value } as Map<String, Any>
        return ResponseEntity.ok(safe)
    }
}

// ── Service → Generated DTO shared converter ─────────────────────

private fun SvcCompatResult.toGenerated(): GCompatResult {
    val missing = requiredFieldsMissing.map { field ->
        CompatDiagnostic(
            field = field,
            message = "Target required field '$field' is missing from mapped source output"
        )
    }
    val mismatches = typeMismatches.map { tm: TypeMismatch ->
        CompatDiagnostic(
            field = tm.field,
            message = "Type mismatch on '${tm.field}': source types [${tm.sourceTypes.joinToString()}] vs target types [${tm.targetTypes.joinToString()}]",
            expectedType = tm.targetTypes.firstOrNull(),
            actualType = tm.sourceTypes.firstOrNull()
        )
    }
    val warnings = warnings.map { msg ->
        CompatDiagnostic(field = "_", message = msg)
    }
    val dto = GCompatResult(compatible = ok)
    dto.sourceFields = resolvedSourceProjectedTypes.size
    dto.targetRequiredCount = requiredFieldsMissing.size
    dto.missingRequired = missing.toMutableList()
    dto.typeMismatches = mismatches.toMutableList()
    dto.unmappedOptional = warnings.toMutableList()
    return dto
}
