package com.fluxion.admin.controller

import com.fluxion.admin.generated.api.SandboxesApi
import com.fluxion.admin.generated.model.SandboxAcquireRequest
import com.fluxion.admin.generated.model.SandboxInstance
import com.fluxion.admin.generated.model.SandboxStatus
import com.fluxion.admin.generated.model.SandboxTicket as GeneratedSandboxTicket
import com.fluxion.admin.service.SandboxManager
import com.fluxion.admin.service.SandboxSummary
import org.slf4j.LoggerFactory
import org.slf4j.warn
import org.springframework.http.HttpStatus
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.RestController
import java.time.LocalDateTime
import java.time.ZoneId
import java.time.format.DateTimeFormatter

/**
 * Admin-facing REST for the debug-sandbox feature.
 *
 * **Contract-driven**: implemented from [SandboxesApi] generated by `doc/openapi.yaml` Sandboxes tag.
 * Controller only implements the interface; no Spring MVC annotations are written manually.
 *
 * ### Typical designer flow
 * 1. User opens the workflow debugger → `acquireSandbox` → returns ticket with
 *    sandbox instance summaries + `routingContext` that MUST be merged into every
 *    subsequent `/internal/debug/execute` body so `builtin:dbExecute` transparently
 *    targets the `sb_<hash>_*` prefixed tables.
 * 2. Designer calls `/internal/debug/execute` with `routingContext` merged in.
 * 3. User closes DebugPanel → `releaseSandboxSession(sessionId)` to DROP cloned
 *    tables eagerly instead of waiting for TTL.
 * 4. Admin tooling can peek or force-release individual sandboxes via the `/{id}`
 *    endpoints.
 */
@RestController
class SandboxController(
    private val sandboxManager: SandboxManager
) : SandboxesApi {
    private val log = LoggerFactory.getLogger(javaClass)

    override fun acquireSandbox(req: SandboxAcquireRequest): ResponseEntity<GeneratedSandboxTicket> = try {
        val ticket = sandboxManager.acquire(
            appId = req.appId,
            ownerSession = req.sessionId,
            ownerUsername = req.username,
            baseResourceIds = req.resourceIds,
            ttlMinutes = req.ttlMinutes?.coerceIn(1, 1440) ?: 240
        )
        val nowMs = System.currentTimeMillis()
        val expireMs = ticket.expiredAt.parseIsoOrNow().toEpochMillis()
        val instances = ticket.instances.map { it.toGenerated() }.toMutableList()
        val total = instances.sumOf { maxOf(0, it.clonedTables) }
        val safeRoutingCtx = (ticket.routingContext as Map<String, Any?>).filterValues { it != null }.toMutableMap() as MutableMap<String, Any>
        ResponseEntity.ok(
            GeneratedSandboxTicket(
                sessionId = ticket.sessionId,
                appId = ticket.appId,
                instances = instances,
                totalClonedTables = total,
                expiresAt = expireMs,
                createdAt = nowMs
            ).apply {
                ownerUsername = req.username
                routingContext = safeRoutingCtx
            }
        )
    } catch (e: IllegalArgumentException) {
        log.warn("acquireSandbox failed: ${e.message}")
        ResponseEntity.badRequest().build()
    }

    override fun releaseSandboxSession(sessionId: String): ResponseEntity<Unit> {
        sandboxManager.releaseSession(sessionId)
        return ResponseEntity.noContent().build()
    }

    override fun peekSandbox(id: Long): ResponseEntity<Unit> =
        // Detailed inspection of sandbox contents is added when Sandbox Explorer ships.
        ResponseEntity.status(HttpStatus.NOT_IMPLEMENTED).build()

    override fun releaseSandbox(id: Long): ResponseEntity<Unit> = try {
        sandboxManager.release(id)
        ResponseEntity.noContent().build()
    } catch (e: IllegalArgumentException) {
        ResponseEntity.notFound().build()
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private fun SandboxSummary.toGenerated(): SandboxInstance {
        val prefix = config["tablePrefix"]?.toString()
            ?: (config["redisDbIndex"]?.let { idx -> "redis-db-$idx" } ?: "")
        val createdCount = (config["createdTables"] as? List<*>)?.size ?: 0
        val status = when (lifecycle) {
            SandboxManager.LIFECYCLE_CREATING -> SandboxStatus.CREATING
            SandboxManager.LIFECYCLE_READY, SandboxManager.LIFECYCLE_IN_USE -> SandboxStatus.READY
            SandboxManager.LIFECYCLE_EXPIRED, SandboxManager.LIFECYCLE_CLEANED -> SandboxStatus.EXPIRED
            SandboxManager.LIFECYCLE_CLEANING -> SandboxStatus.RELEASING
            SandboxManager.LIFECYCLE_FAILED -> SandboxStatus.FAILED
            else -> SandboxStatus.CREATING
        }
        val expireMs = expiredAt.parseIsoOrNow().toEpochMillis()
        val createdAt = (config["_createdAtMs"] as? Long) ?: (expireMs - 60_000L)
        return SandboxInstance(
            id = id,
            resourceId = resourceId,
            tablePrefix = prefix,
            clonedTables = createdCount,
            status = status,
            expiresAt = expireMs,
            createdAt = createdAt
        )
    }

    private fun String.parseIsoOrNow(): LocalDateTime = runCatching {
        LocalDateTime.parse(this, DateTimeFormatter.ISO_DATE_TIME)
    }.getOrDefault(LocalDateTime.now())

    private fun LocalDateTime.toEpochMillis(): Long =
        this.atZone(ZoneId.systemDefault()).toInstant().toEpochMilli()
}
